# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84355226944f5be2062ac8ab5bcafa7d553a1989128b321eed8340fb1987d40c85781a9203392af32e28ceff465e5518bcbbe9e90de63c50c3e43a1f3fcf9d0b

test:
  secret_key_base: 7fc69c58a9fa966ff11d3efc4e2923f296ed61dac1a5c609bc586c0d011e87791677fc37abef06bd8a273e80feb3aa10199aaf5043540f89954d8addbe4a9a49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
